Algoritmo "semnome"
//  
//  
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/07/2017
Var

// Seção de Declarações das variáveis 
       nota:inteiro
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreva("escreva a nota")
leia(nota)
se(nota>=10)entao
escreva("positiva")
senao
escreva("negativa")
fimse

Fimalgoritmo