Algoritmo "semnome"
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 30/09/2017
Var
comprimento,largura,altura,volume:real


Inicio
escreva("escreva o comprimento do paralelipipedo :")
leia(comprimento)
escreva ("escreva a largura do paralelipipedo :")
leia(largura)
escreva("escreva a altura do paralelipipedo :")
leia(altura)
volume <- comprimento*largura*altura
escreva(volume)


Fimalgoritmo